// lib/kpi-templates.ts
// KPI template definitions for each business type

import type { BusinessTypeId } from "@/lib/business-types";

export type TrendGoal = "increase" | "decrease" | "stable";

export interface KpiTemplate {
  id: string;
  label: string;
  description: string;
  trendGoal: TrendGoal;
  // optional hints for mapping to actual data later (Phase 6C)
  group?:
    | "revenue"
    | "cost"
    | "profitability"
    | "retention"
    | "operations"
    | "utilization";
}

export type KpiTemplateMap = Record<BusinessTypeId, KpiTemplate[]>;

export const KPI_TEMPLATES: KpiTemplateMap = {
  saas: [
    {
      id: "mrr",
      label: "Monthly Recurring Revenue (MRR)",
      description: "Total recurring subscription revenue per month.",
      trendGoal: "increase",
      group: "revenue",
    },
    {
      id: "net_mrr_churn",
      label: "Net MRR Churn",
      description:
        "Net loss of MRR from downgrades and cancellations after expansion revenue.",
      trendGoal: "decrease",
      group: "retention",
    },
    {
      id: "cac",
      label: "Customer Acquisition Cost (CAC)",
      description: "Average cost to acquire one new customer.",
      trendGoal: "decrease",
      group: "profitability",
    },
    {
      id: "ltv",
      label: "Lifetime Value (LTV)",
      description: "Estimated lifetime gross profit per customer.",
      trendGoal: "increase",
      group: "profitability",
    },
  ],
  agency: [
    {
      id: "billable_utilization",
      label: "Billable Utilization",
      description: "Share of total hours that are billable to clients.",
      trendGoal: "increase",
      group: "utilization",
    },
    {
      id: "project_margin",
      label: "Project Margin",
      description: "Gross margin per project after direct delivery costs.",
      trendGoal: "increase",
      group: "profitability",
    },
    {
      id: "revenue_per_client",
      label: "Revenue per Client",
      description: "Average revenue generated per active client.",
      trendGoal: "increase",
      group: "revenue",
    },
    {
      id: "dso",
      label: "Days Sales Outstanding (DSO)",
      description: "Average days it takes clients to pay invoices.",
      trendGoal: "decrease",
      group: "operations",
    },
  ],
  fitness_studio: [
    {
      id: "class_utilization",
      label: "Class Utilization Rate",
      description: "Percentage of available spots filled per class.",
      trendGoal: "increase",
      group: "utilization",
    },
    {
      id: "avg_attendance_per_class",
      label: "Average Attendance per Class",
      description: "Average number of attendees per class session.",
      trendGoal: "increase",
      group: "utilization",
    },
    {
      id: "pack_membership_sales",
      label: "Pack & Membership Sales",
      description: "Revenue from class packs and memberships over a period.",
      trendGoal: "increase",
      group: "revenue",
    },
    {
      id: "cancellation_rate",
      label: "Late Cancellation / No-Show Rate",
      description: "Share of bookings cancelled late or not attended.",
      trendGoal: "decrease",
      group: "operations",
    },
    {
      id: "instructor_margin",
      label: "Instructor Margin",
      description: "Revenue generated by an instructor minus their cost.",
      trendGoal: "increase",
      group: "profitability",
    },
  ],
};
